In [1]:
import torch

x = torch.tensor(3., requires_grad=True) # Initialize a tensor with gradient tracking enabled
y = x ** 2

y.backward() # Compute the gradient of y with respect to x
print(x)       # Output: tensor(3., requires_grad=True)
print(x.grad)  # Output: tensor(6.) -> dy/dx = 2 * x = 2 * 3 = 6
print(y)       # Output: tensor(9., grad_fn=<PowBackward0>) -> y = x^2 = 3^2 = 9

tensor(3., requires_grad=True)
tensor(6.)
tensor(9., grad_fn=<PowBackward0>)


In [2]:
import torch.nn as nn

horas = torch.tensor([[1.], [2.], [3.], [4.], [5.], [6.]])  # Input tensor representing hours studied
notas = torch.tensor([[2.5], [4.], [5.5], [7.], [8.], [10.]])  # Target tensor representing grades


In [3]:
modelo = nn.Linear(in_features=1, out_features=1)  # Create a linear regression model with 1 input and 1 output feature

print(modelo)
print(list(modelo.parameters()))  # Output: [Parameter containing: tensor([[0.]]), Parameter containing: tensor([0.])] -> The model has a linear layer with bias

Linear(in_features=1, out_features=1, bias=True)
[Parameter containing:
tensor([[0.6448]], requires_grad=True), Parameter containing:
tensor([0.8564], requires_grad=True)]


In [4]:
loss_fn = nn.MSELoss()  # Define the Mean Squared Error loss function

otimizador = torch.optim.SGD(modelo.parameters(), lr=0.01)  # Define the optimizer (Stochastic Gradient Descent) with learning rate 0.01

In [5]:
print(horas)
print(modelo(horas))  # Output: tensor([[0.], [0.], [0.], [0.], [0.], [0.]], grad_fn=<AddmmBackward0>) -> The model's predictions for the input hours

#Resultado de -> peso @ horas + viés -> weight @ horas + bias
# W e B são inicialmente aleatórios, criados pelo modelo inicial 

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
tensor([[1.5012],
        [2.1460],
        [2.7908],
        [3.4355],
        [4.0803],
        [4.7251]], grad_fn=<AddmmBackward0>)


In [6]:
for epoca in range(201):
    previsao = modelo(horas) #foward
    loss = loss_fn(previsao, notas) #calculo do erro

    otimizador.zero_grad() #zera o gradiente
    loss.backward()        #backward: calcula gradientes
    otimizador.step()      #ajusta peso e viés

    if epoca % 20 == 0:
        print(f"Época {epoca}: loss: {loss.item():.4f}")
        previsoes = modelo(horas)
        for prev in previsao:
            print(f"Previsão: {prev.item():.4f}", end=" | ")

        print()
        # for h, real, prev in zip(horas, notas, previsoes):
        #     print(f"Horas: {h.item():.1f} | Nota real: {real.item():.1f} | Previsto: {prev.item():.2f}")

Época 0: loss: 11.2781
Previsão: 1.5012 | Previsão: 2.1460 | Previsão: 2.7908 | Previsão: 3.4355 | Previsão: 4.0803 | Previsão: 4.7251 | 
Época 20: loss: 0.0294
Previsão: 2.5095 | Previsão: 3.9705 | Previsão: 5.4315 | Previsão: 6.8925 | Previsão: 8.3535 | Previsão: 9.8145 | 
Época 40: loss: 0.0294
Previsão: 2.5109 | Previsão: 3.9720 | Previsão: 5.4331 | Previsão: 6.8941 | Previsão: 8.3552 | Previsão: 9.8163 | 
Época 60: loss: 0.0294
Previsão: 2.5118 | Previsão: 3.9726 | Previsão: 5.4334 | Previsão: 6.8942 | Previsão: 8.3550 | Previsão: 9.8158 | 
Época 80: loss: 0.0294
Previsão: 2.5127 | Previsão: 3.9732 | Previsão: 5.4337 | Previsão: 6.8943 | Previsão: 8.3548 | Previsão: 9.8154 | 
Época 100: loss: 0.0294
Previsão: 2.5134 | Previsão: 3.9737 | Previsão: 5.4340 | Previsão: 6.8944 | Previsão: 8.3547 | Previsão: 9.8150 | 
Época 120: loss: 0.0294
Previsão: 2.5142 | Previsão: 3.9743 | Previsão: 5.4343 | Previsão: 6.8944 | Previsão: 8.3545 | Previsão: 9.8146 | 
Época 140: loss: 0.0294
Previsão

In [7]:
hora_teste = torch.tensor([7.])
print(f"{modelo(hora_teste).item():.4f}")

11.2726
